### ISSUE TITLE
[task] list

### ISSUE THREAD

**Issue by Alice52** [Alice52/issue#56]
## delete task when leaving

- [x] 1. chrome 账号: 以及相关的数据文件
- [x] 2. 微信数据
- [x] 3. 我的 repo 仓库
- [x] 4. vscode 及相关配置
- [x] 5. idea 软件 | workbench 
- [x] 6. datagrip | fastone | listry
- [x] 7. ~/.ssh 目录: github key
- [x] 8. Downloads
- [x] 9. Desktop
- [x] 10. 抽屉，，鼠标，，等现实物品
- [x] 11. 回收站

**Comment by Alice52** [comment]
## task recently

- [ ] 1. graphql
- [ ] 2. consul
- [ ] 3. gin - project-practice
   - pp
- [ ] 4. leetcode-dz
